# Generated by Django 3.0.5 on 2020-11-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('prix', models.FloatField()),
                ('lien', models.CharField(max_length=300)),
                ('marque', models.CharField(max_length=300)),
                ('etat', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('site_officiel', models.CharField(max_length=200)),
            ],
        ),
    ]
